// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/All-Done-Right/douyin-mall-microservice/app/user/internal/core"
	"github.com/All-Done-Right/douyin-mall-microservice/app/user/internal/delivery"
	"github.com/All-Done-Right/douyin-mall-microservice/app/user/internal/repo"
	"github.com/All-Done-Right/douyin-mall-microservice/app/user/internal/usecase"
)

// Injectors from wire.go:

func wireApp() *delivery.UserDelivery {
	context := core.NewContext()
	db := core.NewDB(context)
	mysqlUserRepo := repo.NewMysqlUserRepo(db)
	concreteUserUsecase := usecase.NewConcreteUserUsecase(mysqlUserRepo)
	userDelivery := delivery.NewUserDelivery(concreteUserUsecase)
	return userDelivery
}
