// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/All-Done-Right/douyin-mall-microservice/app/auth/internal/delivery"
	"github.com/All-Done-Right/douyin-mall-microservice/app/auth/internal/usecase"
)

// Injectors from wire.go:

func wireApp() *delivery.AuthDelivery {
	concreteAuthUsecase := usecase.NewConcreteAuthUsecase()
	authDelivery := delivery.NewAuthDelivery(concreteAuthUsecase)
	return authDelivery
}
